- name: Execute report generator
  local_action:
    command: >
      python {{ role_path }}/files/report.py
      "{{ ansible_hostname }}"
      "{{ ansible_distribution }}"
      "{{ ansible_distribution_version }}"
      "{{ srv_type }}"
      "{{ ansible_processor_vcpus }}"
      "{{ ansible_memory_mb.real.total }}"
      "{{ result_disk_1.stdout }}"
      "{{ ansible_default_ipv4.address }}"
      "{{ ansible_default_ipv4.netmask }}"
      "{{ ansible_default_ipv4.gateway }}"
      "{{ yum_cmd }}"
      "{{ result_ntp_2.stdout }}"
      "{{ mon_agt }}"
      "{{ result_monitor.stdout }}"
      "{{ result_bckup.stdout }}"
      "{{ result_ds.stdout }}"
      "{{ result_vmt.stdout }}"
      "{{ result_kdump.stdout }}"
      "{{ build_by }}"
      "{{ qa_by }}"
      "{{ ticket_num }}"
      "{{ client_name }}"
      "{{ os_verification }}"
      "{{ proc_verification }}"
      "{{ sto_verification }}"
      "{{ nw_verification }}"
      "{{ dns_verification }}"
      "{{ dns_domain }}"
      "{{ ad_info }}"
      "{{ osr_out }}"
      "{{ osr_verification }}"
